name: ci
on: [push, pull_request]
jobs:
  build:
    uses: ardencm/ci-shared-workflows/.github/workflows/java-build.yml@v3
    with:
      java-version: "17"
    secrets:
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
